### ISSUE TITLE
Create Services -> Frontend page

### ISSUE THREAD

**Issue by tjwebb** [langateam/langa.io#13]
Services -> Frontend Landing Page
Hero heading: We deliver amazing web experiences using React.js and other modern web technologies.
Subheading: Our expertise and passion for the craft produces solutions that provide real value and serve as an engine of growth for our clients
CTA: Let’s Talk <link to Contact Us form below>
Customers: IBM | XO Group | Expedia
List 3 services/value props: i.e. collaborative approach, agile design, scalable web apps, 
Contact Us form

**Comment by nickten** [comment]
Typo: “mdoern” to “modern” in subheading
