### ISSUE TITLE
Norfolk SVG forced below div

### ISSUE THREAD

**Issue by nogtini** [langateam/langa.io#3]
Need to test on various devices. An absolute positioning should be the fix.

<img width="1020" alt="screen shot 2016-04-15 at 5 54 01 pm" src="https://cloud.githubusercontent.com/assets/5909827/14575935/2f22b544-0333-11e6-8095-58287366ff94.png">

**Comment by wbprice** [comment]
@yejodido Do you see this on http://langa-io-staging.herokuapp.com/?  If not merging and deploying #8 will fix this.
