### ISSUE TITLE
Client logo grid should scale down with viewport.

### ISSUE THREAD

**Issue by wbprice** [langateam/langa.io#32]
![screen shot 2017-03-15 at 10 01 48 am](https://cloud.githubusercontent.com/assets/2590422/23952028/75af0c12-0966-11e7-9353-053a29ea6cb0.png)

**Comment by nogtini** [comment]
Do we want to include the entire set of client logos for mobile? Scrolling through what amounts to 9 clients seems like a poor experience.

**Comment by wbprice** [comment]
3x3 grid might be better.
