### ISSUE TITLE
footer alignment is messed up

### ISSUE THREAD

**Issue by tjwebb** [langateam/langa.io#42]
@yejodido @weyj4 can one of you guys take a look at this today? Also, the team image looks really huge.
<img width="727" alt="screen shot 2017-03-29 at 1 58 04 pm" src="https://cloud.githubusercontent.com/assets/1009114/24468940/d5c1d658-1487-11e7-9d57-e53914dfcedb.png">

**Comment by nogtini** [comment]
Do we have a mockup for what we should be targeting with the footer? Or "just make it look good"?
